package message;

public enum MessageType {
    SERVER_ERROR_EVENT,

    CLIENT_LOGIN_EVENT,
    SERVER_LOGIN_EVENT,

    CLIENT_CREATE_ROOM_EVENT,
    SERVER_CREATE_ROOM_EVENT,

    CLIENT_JOIN_ROOM_EVENT,
    CLIENT_CHANGE_ROOM_SETTING_EVENT,
    CLIENT_GAME_READY_EVENT,
    CLIENT_EXIT_ROOM_EVENT,
    SERVER_ROOM_UPDATE_EVENT,

    CLIENT_ROOM_CHAT_MESSAGE,
    SERVER_ROOM_CHAT_MESSAGE,

    SERVER_REQUEST_TOPIC_EVENT,
    CLIENT_SUGGEST_TOPIC_EVENT,
    SERVER_START_GAME_EVENT,

    CLIENT_DRAW_EVENT,
    SERVER_DRAW_EVENT,

    SERVER_TURN_CHANGE_EVENT,

    CLIENT_GUESS_EVENT,
    SERVER_FINISH_GAME_EVENT,

    CLIENT_VOTE_READY_EVENT,
    SERVER_REQUEST_VOTE_EVENT,
    CLIENT_VOTE_EVENT,
    SERVER_VOTE_EVENT,
    SERVER_FINISH_VOTE_EVENT
}
